### PR TITLE
Addition Of A Password Validator

### PR DESCRIPTION
**Pull request by Mannuel25**
This program validates passwords to match specific rules. A valid password is one that conforms to the following rules:
- Minimum length is 8;
- Maximum length is 12;
- Contains at least one uppercase letter;
- Contains at least one lowercase letter;
- Contains at least a number;
- Contains at least a special character (such as @,+,£,$,%,*^,etc);
- Doesn't contain space(s).

### CODE REVIEW

**Comment by ssm0801** [comment]
Add [this](https://github.com/ssm0801/ScriptAllTheThings/blob/master/basic_info.md) basic info at top of script

**Comment by ssm0801** [comment]
This script can not be considered. Hope you could work on new script.

**Comment by ssm0801** [comment]
This script can not be considered. Hope you could work on new script.

**Comment by Mannuel25** [comment]
Could you please let me make the required changes?

**Comment by ssm0801** [comment]
Actually this could not be considered as script. You can work on new on

**Pull request closed without merging**
