### PR TITLE
Updated the temperature_scale_converter.py

### PR DESCRIPTION
**Pull request by mayankgoyal-13**
1) Added the SI unit of Temperature- The Kelvin Scale
2) Earlier temperature value in decimal was converted to an integer. So, converted the data type to float, so that temperature in 
    decimals can be considered
3) Added comments to make it user-friendly

### CODE REVIEW

**Comment by mayankgoyal-13** [comment]
@ssm0801 pls verify my code. I have more features for the temperature converter.

**Comment by mayankgoyal-13** [comment]
@herkura @niyoj

**Comment by mayankgoyal-13** [comment]
It is a sincere request @ssm0801 to label it hacktoberfest-accepted

**Comment by ssm0801** [comment]
Done

**Pull request merged**
