### PR TITLE
Adds new script Temperature Scale Converter

### PR DESCRIPTION
**Pull request by niyoj**
# Summary of the changes
- New folder was created as it was a separate script i.e. `Temperature Scale Converter` inside the root directory,
- Python script was added and named as `temp.py` inside the folder created above,
- The script `temp.py` is used to convert temperature scales.

### CODE REVIEW

**Comment by ssm0801** [comment]
Please check for typos and name the .py as temperature_scale_converter.py

**Comment by ssm0801** [comment]
Add this kind of info at beginning of .py file and remove those two starting lines
"""
Text to Handwriting
-Convert any text into handwriting and create image
Author : Sudhanshu Motewar [github hyperlink]
Date : 24/09/21
"""

**Comment by niyoj** [comment]
Changes have been made.

**Review by ssm0801 — APPROVED** [review]

**Comment by ssm0801** [comment]
Can you add row for this script in table of readme file

**Pull request merged**
